### ISSUE TITLE
Upload/delete files 

### ISSUE THREAD

**Issue by sumanksk2006** [TimOliver/TOSMBClient#16]
Is there a way to upload files, create directories to connected SMB server and also delete existing files/directories in SMB using libdsm API

**Comment by TimOliver** [comment]
Not in `TOSMBClient` at the moment. The functionality is there in `libdsm` but I haven't had time to implement it. It's not a high priority for me since it's not a feature I need in the app I built this library for.

If you want to try writing it yourself, feel free to do so and file a PR!

This feature has already been requested in https://github.com/TimOliver/TOSMBClient/issues/3, so I'm closing this issue in favour of that one.
