### ISSUE TITLE
build 1.0.6 code "_clock_gettime" issue

### ISSUE THREAD

**Issue by bernayu** [TimOliver/TOSMBClient#36]
Hi Tim, 
I downloaded 1.0.6, build the code then got error "_clock_gettime" also noticed the latest version in pod spec is 1.0.5. I guess this version hasn't ready yet, has it? 
I'm interested with libdsm, i'm hoping you can help me to create static library of libdsm from my mac. any help is appreciated.
Thanks for developing this wrapper for iOS!

**Comment by TimOliver** [comment]
Hi @bernayu!

Yeah, I'm still playing with the latest version to push to CocoaPods. Per the authors of libdsm's request, I need to ensure the framework is explicitly embedded as a dynamic framework in order to comply with their LGPL requirements.

Sure! This is the build script I use to compile the static version of libdsm. It should be possible to modify it for Mac easily enough: https://gist.github.com/TimOliver/0a67da72b097c42c7552043aca48bc86

Thanks a lot! I'm glad you're finding it useful! I'm kind of dumbfounded there are no other SMB implementations for iOS publicly out there!

**Comment by bernayu** [comment]
Hi Tim, thanks a lot! 
just tried the script, libtasn1.a was successfully created but failed for libdsm.a. I tried to look into thousand line, but not sure what I'm looking for. i just run the script from terminal, I wonder if I should do something before run it. Any idea?

**Comment by TimOliver** [comment]
No worries! You probably don't need to use a lot of that script; most of it is compiling the binary in the necessary ARM architecture slices. You'll have to change a few settings, like the SDK path in order to get it to build for Mac.

I don't really have the time to help more than that though, sorry! If it's failing, it usually helps to just copy/paste the lot to a text file and then do a search for 'error'. :)

**Comment by bernayu** [comment]
Thanks Tim :) 
I think the script is working fine. the error states some files are missing. first was bootstrap, I guess I had issue when downloading it. 
Second is spnego_asn1.c 

asn1Parser -o contrib/spnego/spnego_asn1.c -n spnego_asn1_conf contrib/spnego/spnego.asn1
make[1]: asn1Parser: No such file or directory
make[1]: **\* [contrib/spnego/spnego_asn1.c] Error 1
make: **\* [all] Error 2

not sure what it is, but I can't find it in master branch. do you know where I can find it? Thanks a lot!

**Comment by TimOliver** [comment]
I had a few minutes tonight so I had a bit of a play. :)

https://gist.github.com/TimOliver/d4d2f16f4b6960ff22b6190e0d4811df

Make sure you build with `sudo` to make sure there are no permission errors.

**Comment by bernayu** [comment]
Thank you Tim really appreciated,
unfortunately both libs, libtasn1 and libdsm failed. here's some error lines. 

checking for x86_64-apple-darwin16.0.0-gcc... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Users/Bear/Source/libdsm-local/libtasn1-4.9':
configure: error: C compiler cannot create executables
See`config.log' for more details

I used 'sudo bash libdsm_build_macos.sh', is it correct?

[config.log.zip](https://github.com/TimOliver/TOSMBClient/files/583257/config.log.zip)

**Comment by TimOliver** [comment]
Hmm, that's weird. `x86_64-apple-darwin16.0.0` is fine for me. I'm on the very latest version of macOS though, so that might explain it.

Ah well. Here's the version I got when I ran the build script. You'll need to rename the `#import` references to the headers in there in order for Xcode to properly recognize them, but aside from that, it SHOULD just work. :)

Let me know if you need anymore help. In the meantime, I'm going to see if I can integrate this build script into the Xcode project itself so it's not such a hassle on its own. Hope that helps! :)

[libdsm-macos.zip](https://github.com/TimOliver/TOSMBClient/files/584049/libdsm-macos.zip)

**Comment by bernayu** [comment]
sorry for delay response. 
yeah mine was x86_64-apple-darwin15.6.0, unfortunately changed it to latest one or update the script doesn't fix the asn1Parser issue. But thanks for attachment :)

just wondering, since it was built in macOS SDK rather than iOS, will we get another issue in the future? 
Thanks a lot!
