### ISSUE TITLE
App crashes when upload a file which size is bigger than 5M

### ISSUE THREAD

**Issue by Deerdev** [TimOliver/TOSMBClient#41]

**Comment by TimOliver** [comment]
Um. Are there any error messages that appear when it crashes?

**Comment by Deerdev** [comment]
![img_1888](https://cloud.githubusercontent.com/assets/6970468/20959590/b5a9f3ee-bc96-11e6-923b-54cfa11a2a28.JPG)

throw "EXC_BAD_ACCESS" when go into the loop first time；

**Comment by xorander00** [comment]
I'm having the same issue.  Haven't had the chance to fully figure it out, but it seems that it might be an issue within libdsm.  Everything passed into smb_fwrite seems kosher.  I confirmed that the buffer is valid and that the buffer size was properly specified.  I'm going to try to take a deeper look at it next week, but if anyone else finds anything in the meantime, I'd like to hear about it here :)

**Comment by TimOliver** [comment]
Hmm, if everything on our end seems kosher, it might be a `libdsm` level issue then...

**Comment by xorander00** [comment]
Possibly, but I wouldn't assume that just yet.  Ultimately, it's libdsm being unable to access the data buffer.  Currently, I suspect that it's either being free()'ed/released too early (whether it's in TOSMBClient or libdsm) or it's some kind of access issue (threading?).  I'm not too familiar with Objective-C, but I have plenty of experience with C and LLVM, so I'll dig in later this week.

In my case, I get that error whenever the data being written out is greater than the write buffer size (64k - header size).  It happens way below 5MB for me.  I tried playing around with the smb_fopen flags, but to no avail.  I also tried reducing the buffer size to see if the header size might have been changed somehow, but that didn't work either.  It does create create the file though, it just ends up being 0 bytes.

Oh, and also, I found a small bug a week ago, but haven't had the chance to submit a PR yet (don't do this very often, sorry).  I can do one later this week, but it's literally a one-liner if you want to make the quick change yourself.  It's in TOSMBSessionUploadTask.m @ line 222.  Right after the free(buffer) call, I added smb_fclose(self.smbSession, fileID).  Otherwise it holds the file lock and the file can't be deleted until libdsm releases the lock.  Found it while debugging this issue, ended up with a bunch of 0-byte files that I couldn't delete lol.

**Comment by kamsont** [comment]
Any news on this issue? I'm having trouble uploading files >150KB. Other people claim that they were able to upload >1GB using libdsm ([post](https://github.com/videolabs/libdsm/issues/85) from video labs)

**Comment by xorander00** [comment]
I'm actually investigating it further later today & tomorrow.  I'm not yet 100% convinced that it's a libdsm issue.  I still suspect that it has to do with the Objective-C malloc'ed memory buffer.  Alternatively, it could be a protocol-specific issue as well.  I actually spent some time a few days ago reading up on the SMB spec and will now be going through the libdsm code a bit more along with the code in this repo.

If I find something, I'll post here in the coming few days.

**Comment by xnz23** [comment]
Same issue here!!!

**Comment by ikonion-digitale-medien-gmbh** [comment]
Hey this is very interesting - got the same problem... download is no problem at any size but upload is limited to small files. @xorander00 did you already figured out if the problem is within libdsm? Sadly i`m not experienced enough in C.

**Comment by DemianSteelstone** [comment]
I'm sure that libdsm works fine. I have no problems with it in my fork.
also you can try to decrease chunk size

**Comment by kamsont** [comment]
I tried to upload bigger files with your forked version - no success, same exception thrown. Could you specify what you mean with chunk size? The buffer size?

**Comment by DemianSteelstone** [comment]
Yep, I mean buffer size.
I can successfully upload files more then 30 mb
Which branch you're try?

**Comment by kamsont** [comment]
You are right. I have been using the master branch for a test. In the developer branch the upload is passing without exception. Is it right that all you had to do is writing the file to your device first before uploading to avoid the malloc problem?

**Comment by DemianSteelstone** [comment]
I have changed write with data to stream writing to avoid problems with the lack of memory and reduce buffer size to 64000 bytes. Don't know why, but it crashes with larger size.

**Comment by narendra-ct** [comment]
@sweetfish I'm not sure why this happening, i faced same issue while using this lib, for the solution i tried by changing buffer size 

**#define BUFFER_UPLOAD_SIZE  60000**

and refer following code you may get some idea.

    _fp = fopen([filePath UTF8String],"r");
    NSFileHandle *fileHandle = [NSFileHandle fileHandleForReadingAtPath:filePath];
    self.countOfBytesExpectedToReceive = (ssize_t)[fileHandle seekToEndOfFile];
    
    BOOL success = TRUE;
    int64_t _length = 0;
    if (_fp != NULL)
    {
        while (_read_length != 0)
        {
            //Write the bytes to the network device
            @autoreleasepool
            {
                _read_length = fread(_buffer, 1, BUFFER_UPLOAD_SIZE, _fp);
                if (_read_length != 0 && _read_length > 0)
                {
                    _length = smb_fwrite(_uploadSession, uploadFileID, _buffer, _read_length);
                    if (_length > 0)
                    {
                        self.countOfBytesReceived += _read_length;
                        progress(_length,self.countOfBytesReceived,self.countOfBytesExpectedToReceive);
                    }
                    else
                    {
                        _read_length = 0;
                        success = FALSE;
                    }
                }
            }
            
            if (weakOperation.isCancelled)
            {
                _read_length = 0;
                success = FALSE;
                //                break;
            }
        }
        
    }
    else
    {
        success = FALSE;
    }
    
    if (_buffer != NULL) {
        free(_buffer);
    }

Thanks,
Narendra.

**Comment by Deerdev** [comment]
@narendra-ct Thanks, 
I changed buffer size, it's ok now.

Here is my code, may help to others:
<img width="1420" alt="wx20170215-161913 2x" src="https://cloud.githubusercontent.com/assets/6970468/22966188/0cc2c368-f39c-11e6-970c-9c7cda40294c.png">

**Comment by TimOliver** [comment]
Oh awesome! Nicely done! Can you please file a PR with those updates? :)

**Comment by Deerdev** [comment]
Ok, let me do more test.
